import 'package:get/get.dart';

class Masseges extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        'en_US': {
          'Welcome to my demo App': 'Welcome to my demo App',
          'user name': 'user name',
          'password': 'password',
          'forgot password': 'forgot password',
          'Sign In': 'Sign In',
          'item deleted': 'item deleted',
          'undo': 'undo',
          'please add some details': 'please add some details',
          'chart': 'chart',
          'Add some details': 'Add some details',
          'go to main page': 'go to main page',
          'log out': 'log out',
          'language': 'language',
          'invalid value': 'invalid value',
          '[please make sure that you have entered valid phone number,email,firstname,lastname or fill all objects]':
              '[please make sure that you have entered valid phone number,email,firstname,lastname or fill all objects]',
          'OK': 'OK',
          'write your first name': 'write your first name',
          'write your last name': 'write your last name',
          'write your email': 'write your email',
          'write ur own phone number': 'write ur own phone number',
          'save Detail': 'save Detail',
          'cancel': 'cancel',
          'show me current  location': 'show me current  location',
          'show me commends': 'show me commends',
          'image selection': 'image selection',
          'back': 'back',
          'back to main page':'back to main page',
          'pick Image':'pick Image',
          'login page':'login page',
          'main screen':'main screen',
        },
        'ar_QA': {
          'Welcome to my demo App': 'به برنامه من خوش آمدید',
          'user name': 'نام کاربری',
          'password': 'رمز عبور',
          'forgot password': ' رمز رو فراموش کردی !',
          'Sign In': 'ورود',
          'item deleted': ' محتوا حذف شد',
          'undo': 'برگشت محتوا',
          'please add some details': 'لطفا جزییات مورد نظر را اظافه کنید',
          'chart': 'چارت',
          'Add some details': 'جزییات مورد نظر را اظافه کنید',
          'go to main page': 'صفحه اصلی',
          'log out': 'خروج',
          'language': 'زبان',
          'invalid value': 'مفداردهی نا معتبر',
          '[please make sure that you have entered valid phone number,email,firstname,lastname or fill all objects]':
              '[لطفا از درست بودن مقادیر داده شده از قبیل نام،نام خانوادگی،ایمیل ، تلفن همراه و همچنین جایگزاری آنها اطمینان حاصل فرمایید]',
          'OK': 'باشه',
          'write your first name': 'نام خود را وارد کنید',
          'write your last name': 'نام خانوادگی خود را وارد کنید',
          'write your email': 'ایمیل خود را وارد کنید',
          'write ur own phone number': 'تلفن همراه خود را وارد کنید',
          'save Detail': 'ذخیره داده ها',
          'cancel': 'بی خیال !',
          'show me current  location': 'موقیعت مکانی من رو نشون بده',
          'show me commends': 'نمایش کامنت ها',
          'image selection': 'انتخاب عکس',
          'back': 'بازگشت',
          'back to main page':'بازگشت به صفحه اصلی',
          'pick Image':'انتخاب عکس',
          'login page':'صفحه ورود',
          'main screen':'صفحه اصلی',
        }
      };
}
